### ISSUE TITLE
error when running basically any command

### ISSUE THREAD

**Issue by NotAShelf** [xNitrate/StreamLine#2]
backend servers - paper 1.16.5, b496
proxy - waterfall 1.16.7, b398
luckperms version - 5.2
viaversion - 3.2.1 

basically when any command is ran, this error will show up

````[18:53:15 WARN]: Error in dispatching command
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
        at net.plasmere.streamline.utils.MessagingUtils.sendBUserMessage(MessagingUtils.java:298) ~[?:?]
        at net.plasmere.streamline.commands.GuildCommand.execute(GuildCommand.java:35) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:197) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:148) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:158) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:81) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by xNitrate** [comment]
Man... I thought I fixed this bug... I will look into this. Thanks! :D

**Comment by xNitrate** [comment]
Contact me here (if you can): https://discord.gg/tny494zXfn

I'm not seeing anything on my end that would make it do that. I'm not saying that there isn't a bug, but as of right now, I don't see one.

So, join that Discord server so that I can 1) give you an updated .jar and 2) so I can help you if that doesn't work.

**Comment by xNitrate** [comment]
Is it fixed?
