### ISSUE TITLE
Velocity Discord Boosts Error

### ISSUE THREAD

**Issue by jacklollz2** [xNitrate/StreamLine#6]
I have boosts disabled in the config, yet it's still running this function. Additionally I'm receiving the error:

```
[18:45:32 ERROR]: Exception in task net.plasmere.streamline.objects.timers.OneSecondTimer@6b439371 by plugin StreamLine
java.lang.NullPointerException: Cannot invoke "net.plasmere.streamline.objects.configs.DiscordData.getBoostQueue()" because "net.plasmere.streamline.StreamLine.discordData" is null
        at net.plasmere.streamline.utils.PlayerUtils.tickBoosts(PlayerUtils.java:1891) ~[?:?]
        at net.plasmere.streamline.objects.timers.OneSecondTimer.done(OneSecondTimer.java:102) ~[?:?]
        at net.plasmere.streamline.objects.timers.OneSecondTimer.run(OneSecondTimer.java:37) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:203) ~[velocity-3.1.1-98.jar:3.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

Java 17.0.1 2021-10-19 LTS
velocity-3.1.1-98
Oracle Linux Server 7.9

**Comment by xNitrate** [comment]
Is this fixed in the latest versions?

**Comment by xNitrate** [comment]
This has been fixed. :)
