### ISSUE TITLE
Issue - Velocity

### ISSUE THREAD

**Issue by MANAWARE** [xNitrate/StreamLine#7]
>.... [08:31:36 INFO]: [connected player] CivKev (/MY IP XXXXXX) has connected
>.... [08:31:36 ERROR]: Couldn't pass PostLoginEvent to streamline
java.lang.NoClassDefFoundError: Could not initialize class net.plasmere.streamline.utils.sql.DataSource
at net.plasmere.streamline.listeners.JoinLeaveListener.onJoin(JoinLeaveListener.java:84) ~[?:?]
at net.plasmere.streamline.listeners.Lmbda$33.execute(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.1-98.jar:3.1.1]
at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.1-98.jar:3.1.1]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.1-98.jar:3.1.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
>.... [08:31:36 INFO]: [server connection] CivKev -> Hub has connected

**Comment by xNitrate** [comment]
This is fixed in the pre-release. :) If you join the Discord, I can give it to you.
